version: '3.8'
services:
  productservice:
    build: ./ProductService
    ports: ["5003:8080"]
  orderservice:
    build: ./OrderService
    ports: ["5002:8080"]
  apigateway:
    build: ./ApiGateway
    ports: ["5000:80"]
    depends_on: [productservice, orderservice]