version: '3.8'
services:
  productservice:
    build: ./ProductService
    ports: ["5003:8080"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  orderservice:
    build: ./OrderService
    ports: ["5002:8080"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  apigateway:
    build: ./ApiGateway
    ports: ["5000:8080"]
    depends_on: [productservice, orderservice]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development